name: CI

on:
  push:
    branches: [ test-action ]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Sonarqube installation
        run: |
          sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
          sudo apt-get -y install unzip
          sudo unzip sonarqube-7.3.zip -d /opt
          sudo mv /opt/sonarqube-7.3 /opt/sonarqube

      - name: Set up sonar-scan
        run: |
          set -x
          export LIBDAP_BUILD=sonar
          ./configure --disable-dependency-tracking  --prefix=$prefix --enable-developer --enable-coverage
          build-wrapper-linux-x86-64 --out-dir bw-output make -j7
          sonar-scanner -Dsonar.login=$SONAR_LOGIN
          curl -s https://sonarcloud.io/api/project_badges/quality_gate?project=OPENDAP-libdap4 | grep "QUALITY GATE PASS"

         
