name: CI

on:
  push:
    branches: [ test-action ]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Download & install sonar-scanner
        run: |
          set -x
          sudo mkdir /downloads/sonar-scanner -p
          cd /downloads/sonar-scanner
          echo "downloading sonar-scanner...."
          sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
          echo "Download completed."
          echo "Unzipping downloaded file...."
          sudo unzip sonar-scanner-cli-4.2.0.1873-linux.zip
          echo "Unzip complete"
          sudo mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
          echo "Installation completed successfully."
          echo "You can use sonar-scanner!"
    
      - name: current directory
        run: |
          set -x
          pwd
          cd /downloads/sonar-scanner/conf/sonar-scanner.properties
          pwd
###
