name: CI

on:
  push:
    branches: [ test-action ]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Download & install sonar-scanner
        run: |
          set -x
          sudo mkdir /downloads/sonar-scanner -p
          cd /downloads/sonar-scanner
          sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
          sudo unzip sonar-scanner-cli-4.2.0.1873-linux.zip -d /opt/
          ls -lart
          sudo mv /opt/sonar-scanner-4.2.0.1873-linux/ /opt/sonar-scanner
          ls /opt/sonar-scanner
          cd /opt/sonar-scanner
          pwd

