name: CI

on:
  push:
    branches: [ test-action ]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Sonarqube installation
        run: |
          sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
          sudo apt-get -y install unzip
          sudo unzip sonarqube-7.3.zip -d /opt
          sudo mv /opt/sonarqube-7.3 /opt/sonarqube
          sudo chown -R admin:admin /opt/sonarqube/
         
